"""The core's own geometry must equal the Python board's, table for table.

The board was the one part of the game the C++ core could not produce for
itself: it loaded tables generated by ``diamond.contract.board`` and exported by
``diamond.alphazero.native.topology``. It generates them now
(``native/src/topology_gen.cpp``), which is what makes a build with no Python
self-sufficient rather than merely supplied.

Two implementations of the same construction is exactly the risk the migration
exists to manage, so they are compared here on every entry. ``topology_test``
makes the same comparison on the C++ side against the frozen export; this one
runs it against the live Python board, which is what catches a change to the
board that nobody re-froze.

It retires with the Python board, and the frozen tables in ``tests/golden`` --
which the deployment artifact also ships -- become the only reference.
"""

from __future__ import annotations

import pytest

from diamond.alphazero.native import native_module
from diamond.alphazero.native.topology import topology_tables

pytestmark = pytest.mark.skipif(
    native_module() is None, reason="the native extension is not built"
)

TABLES = (
    "neighbour",
    "camp_positions",
    "pairwise_distance",
    "physical_to_canonical",
    "canonical_to_physical",
)


def _native_tables() -> dict:
    module = native_module()
    assert module is not None
    return module.export_tables()


def test_the_extension_configures_itself_without_being_handed_tables() -> None:
    module = native_module()
    assert module is not None
    assert module.is_configured(), (
        "the extension imported unconfigured: it no longer derives its own "
        "geometry, and every caller is one step from a topology error"
    )


def test_the_generated_tables_equal_the_python_board() -> None:
    native = _native_tables()
    python = topology_tables()

    assert native["board_size"] == python["board_size"]
    assert native["directions"] == python["directions"]
    for name in TABLES:
        native_rows = [list(row) for row in native[name]]
        python_rows = [list(row) for row in python[name]]
        assert native_rows == python_rows, (
            f"{name} differs between the C++ construction and the Python board. "
            "Position ids, camp order and the canonical rotation are the game's "
            "vocabulary; a board that numbers its holes differently is a "
            "different game."
        )


def test_the_canonical_rotation_is_a_bijection_in_both_directions() -> None:
    """Cheap, and the one property a table copy could satisfy while being wrong."""
    native = _native_tables()
    forward = native["physical_to_canonical"]
    inverse = native["canonical_to_physical"]
    size = native["board_size"]

    for camp, (to_canonical, to_physical) in enumerate(zip(forward, inverse)):
        assert sorted(to_canonical) == list(range(size)), f"camp {camp} is not a bijection"
        for physical in range(size):
            assert to_physical[to_canonical[physical]] == physical, (
                f"camp {camp} does not round-trip position {physical}"
            )
